### ISSUE TITLE
Control DiffViewer: doesn't show text but color only

### ISSUE THREAD

**Issue by cpallotti73** [mmanela/diffplex#79]
I'm probably wrong, but the control displays the different colors in the differences lines but without text (see you image attached).
Same problem if set 'ShowInline'.
What am I doing wrong?
![DiffViewer](https://user-images.githubusercontent.com/59970792/115854276-5f563900-a42a-11eb-81a7-1b0dc07bdb0b.PNG)

I use VS2019 + .net framework 4.6.1

Thanks in advance

**Comment by mmanela** [comment]
@kingcean  Can you take a look?

**Comment by kingcean** [comment]
Hi @cpallotti73 could you please try to set `Foreground` property by a color or any kind of `Brush` to have a test?

**Comment by mmanela** [comment]
Since I haven't heard back from @cpallotti73 , closing for now

**Comment by Scandal-UK** [comment]
I get this behaviour as well - no matter what I do. To begin with, I thought it was due to my high-DPI monitor but it can be consistently reproduced on all the dev machines that I have. Presumably the "ElementHost" is playing up??

**Comment by kingcean** [comment]
Hi @Scandal-UK could you please try to set Foreground property by a color to have a test? And does this happen in WinForms or WPF application?

**Comment by Scandal-UK** [comment]
I have tried that - and even setting the font. This is WinForms (which I think just uses an ElementHost? I haven't looked closely).

**Comment by kingcean** [comment]
Could you please confirm if you are running the project `DiffPlex.WindowsForms.Demo`? It is demo of WinForms application.

![DiffPlex.WindowsForms.Demo project](https://user-images.githubusercontent.com/1724940/131769628-f079a9d7-c6f2-4756-8880-1511920b9879.png)

**Comment by Scandal-UK** [comment]
Of course not, I followed the instructions on the front page?? I have created my own control now with two RichTextBox instances in a SplitContainer (with synchronised scrolling), but I'd rather use your control.

Steps to reproduce:

- Create new WinForms project (targeting .NET 5 or .NET Core 3.1)
- Add NuGet package: DiffPlex.Wpf
- Drop DiffViewer from toolbox onto form (optionally set Dock to Fill)
- Add OldText and NewText values in code-behind (either in constructor or Load event)
- Run the solution

**Comment by kingcean** [comment]
Could you please run the demo `DiffPlex.WindowsForms.Demo` mentioned above to have a test? Or run `net5.0-windows\DiffPlex.WindowsForms.Demo.exe` in [DiffPlex.Win32.Demo.zip](https://github.com/mmanela/diffplex/files/7109108/DiffPlex.Win32.Demo.zip) which I built locally.

- If it works well, could you please compare the code between yours and [the one in demo](https://github.com/mmanela/diffplex/blob/eccf6c1d548bca287d27068e71e7e1fd133c60d7/DiffPlex.WindowsForms.Demo/MainForm.cs#L37) and let me know if I can provide any help?
- If not, could you please share details information about your environment (like OS version, language and DPI scale) to me so that I can try to repro?

![Screenshot](https://user-images.githubusercontent.com/1724940/132080672-ef9b161d-ced9-4977-9b23-3f18c9c531cb.jpg)
